import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            Create <span className={styles.pinkSpan}>T3</span> App
          </h1>
          <div className={styles.cardRow}>
            <Link
              className={styles.card}
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className={styles.cardTitle}>First Steps →</h3>
              <div className={styles.cardText}>
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className={styles.card}
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className={styles.cardTitle}>Documentation →</h3>
              <div className={styles.cardText}>
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
          <CrudShowcase />
        </div>
      </main>
    </>
  );
};

export default Home;

const CrudShowcase = () => {
  const example = api.example.getAll.useQuery();
  const utils = api.useContext();
  const create = api.example.create.useMutation({
    onSettled: () => utils.example.invalidate(),
  });

  if (!example.data) {
    return (
      <p className={styles.crudNoData}>
        Loading - if this is stuck, check First Steps
      </p>
    );
  }

  return (
    <div className={styles.showcaseContainer}>
      <button className={styles.showcaseButton} onClick={() => create.mutate()}>
        Create
      </button>
      <p className={styles.crudText}>
        You have created {example.data.length} item(s)
      </p>
    </div>
  );
};
