import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome to the T3 Stack!</h1>
        <p>Your project has been bootstrapped using the create-t3-app CLI</p>
      </main>
    </div>
  );
};

export default Home;
