import type { NextPage } from "next";
import Head from "next/head";
// imports

const Home: NextPage = () => {
  // usage
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>
          Create <span>T3</span> App
        </h1>

        <div>
          <h3>This Stack uses:-</h3>
          <ul>
            <li>
              <a href="https://nextjs.org" target="_blank">
                Next.js
              </a>
            </li>
            <li>
              <a href="https://typescriptlang.org" target="_blank">
                TypeScript
              </a>
            </li>
          </ul>
        </div>
      </div>
    </>
  );
};

export default Home;
