import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col items-center justify-center h-screen p-4">
        <h2 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Create <span className="text-purple-300">T3</span> App
        </h2>
        <p className="text-2xl text-gray-700">This stack uses</p>
        <div className="grid gap-3 pt-3 mt-3 text-center md:grid-cols-3 lg:w-2/3">
          <div className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl cursor-pointer motion-safe:hover:scale-105">
            <h2 className="text-lg text-gray-700">NextJS</h2>
            <p className="text-sm text-gray-600">
              The React framework for production
            </p>
            <a
              className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
              href="https://nextjs.org/"
              target="_blank"
              rel="noreferrer"
            >
              Documentation
            </a>
          </div>
          <div className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl cursor-pointer motion-safe:hover:scale-105">
            <h2 className="text-lg text-gray-700">TypeScript</h2>
            <p className="text-sm text-gray-600">
              Strongly typed programming language that builds on JavaScript,
              giving you better tooling at any scale
            </p>
            <a
              className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
              href="https://www.typescriptlang.org/"
              target="_blank"
              rel="noreferrer"
            >
              Documentation
            </a>
          </div>
          <div className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl cursor-pointer motion-safe:hover:scale-105">
            <h2 className="text-lg text-gray-700">TailwindCSS</h2>
            <p className="text-sm text-gray-600">
              Rapidly build modern websites without ever leaving your HTML
            </p>
            <a
              className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
              href="https://tailwindcss.com/"
              target="_blank"
              rel="noreferrer"
            >
              Documentation
            </a>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
