import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.proxy.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>
          Create <span>T3</span> App
        </h1>
        <div>
          <h3>This stack uses:</h3>
          <ul>
            <Technology
              name={"NextJS"}
              description={"The React framework for production"}
              documentation={"https://nextjs.org/"}
            />
            <Technology
              name={"tRPC"}
              description={"End-to-end typesafe APIs made easy"}
              documentation={"https://trpc.io/"}
            />
            <Technology
              name={"TypeScript"}
              description={
                "Strongly typed programming language that builds on JavaScript, giving you better tooling at any scale"
              }
              documentation={"https://www.typescriptlang.org/"}
            />
          </ul>
          <div className="flex items-center justify-center w-full pt-6 text-2xl text-blue-500">
            {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
          </div>
        </div>
      </div>
    </>
  );
};

interface TechnologyProps {
  name: string;
  description: string;
  documentation: string;
}

const Technology: React.FC<TechnologyProps> = (props) => {
  return (
    <>
      <li>
        <a href={props.documentation} target="_blank" rel="noreferrer">
          {props.name}
        </a>
      </li>
    </>
  );
};

export default Home;
